// Phase 1 persona registry. Keep this file data-only so later UI and physics
// phases can consume the same stories without importing browser code.
export const PERSONAS = [
  {
    id: "amara",
    name: "Amara",
    region: "West Africa",
    story: "Lagos apartment with 6–8 hours of load-shedding each day.",
    profile: "Lagos, Nigeria",
    appliances: [
      "Refrigerator (modern, mid-size)",
      "Ceiling or desk fan",
      "Phone charger",
      "LED light bulb",
    ],
    dailyKwh: 3,
    tariff: 0.42,
    currency: "NGN",
    goal: { mode: "offgrid", tier: "tier99" },
    chemistry: "naion",
    bounds: { pvKw: [0.1, 50], battKwh: [0.1, 300], paybackYears: [0, 100] },
  },
  {
    id: "chandra",
    name: "Chandra",
    region: "South Asia",
    story: "Delhi rural proxy with a monsoon season and a well-pump surge.",
    profile: "Delhi, India",
    appliances: [
      "Deep well pump (submersible, 240V)",
      "Refrigerator (modern, mid-size)",
      "Ceiling or desk fan",
      "LED light bulb",
    ],
    dailyKwh: 8,
    tariff: 0.12,
    currency: "INR",
    goal: { mode: "offgrid", tier: "tier99" },
    chemistry: "naion",
    bounds: { pvKw: [0.1, 50], battKwh: [0.1, 300], paybackYears: [0, 100] },
  },
  {
    id: "kofi",
    name: "Kofi",
    region: "West Africa",
    story: "Accra health clinic protecting a vaccine refrigerator in humidity.",
    profile: "Accra, Ghana",
    appliances: [
      "Refrigerator (modern, mid-size)",
      "Chest freezer",
      "Ceiling or desk fan",
      "LED light bulb",
    ],
    dailyKwh: 4,
    tariff: 0.22,
    currency: "GHS",
    goal: { mode: "offgrid", tier: "tier99" },
    chemistry: "lfp",
    bounds: { pvKw: [0.1, 50], battKwh: [0.1, 300], paybackYears: [0, 100] },
  },
  {
    id: "sofia",
    name: "Sofia",
    region: "Southern Europe",
    story: "Madrid home using grid-tie solar with a feed-in tariff.",
    profile: "Madrid, Spain",
    appliances: [
      "Refrigerator (modern, mid-size)",
      "LED light bulb",
      "Washing machine",
      "Laptop or desktop computer",
    ],
    dailyKwh: 15,
    tariff: 0.28,
    currency: "EUR",
    goal: { mode: "gridtie", cut: 0.8 },
    chemistry: "lfp",
    bounds: { pvKw: [0.1, 60], battKwh: [0, 150], paybackYears: [0, 100] },
  },
  {
    id: "javier",
    name: "Javier",
    region: "North America",
    story: "Mexico City mountain proxy where autonomy matters through winter.",
    profile: "Mexico City, Mexico",
    appliances: [
      "Refrigerator (modern, mid-size)",
      "Water pump (shallow/pressure tank 120V)",
      "LED light bulb",
      "Phone charger",
    ],
    dailyKwh: 6,
    tariff: 0.19,
    currency: "MXN",
    goal: { mode: "offgrid", tier: "tier99" },
    chemistry: "lfp",
    bounds: { pvKw: [0.1, 50], battKwh: [0.1, 300], paybackYears: [0, 100] },
  },
  {
    id: "maria",
    name: "Maria",
    region: "South America",
    story: "São Paulo Amazon proxy with an isolated, rain-season load.",
    profile: "São Paulo, Brazil",
    appliances: [
      "Refrigerator (modern, mid-size)",
      "Chest freezer",
      "Water pump (shallow/pressure tank 120V)",
      "LED light bulb",
    ],
    dailyKwh: 12,
    tariff: 0.2,
    currency: "BRL",
    goal: { mode: "offgrid", tier: "tier99" },
    chemistry: "lfp",
    bounds: { pvKw: [0.1, 50], battKwh: [0.1, 300], paybackYears: [0, 100] },
  },
  {
    id: "ping",
    name: "Ping",
    region: "Southeast Asia",
    story: "Jakarta home with an irrigation pump in humid weather.",
    profile: "Jakarta, Indonesia",
    appliances: [
      "Water pump (shallow/pressure tank 120V)",
      "Refrigerator (modern, mid-size)",
      "Ceiling or desk fan",
      "LED light bulb",
    ],
    dailyKwh: 5,
    tariff: 0.1,
    currency: "IDR",
    goal: { mode: "offgrid", tier: "tier99" },
    chemistry: "lfp",
    bounds: { pvKw: [0.1, 50], battKwh: [0.1, 300], paybackYears: [0, 100] },
  },
  {
    id: "yuki",
    name: "Yuki",
    region: "East Asia",
    story: "Tokyo winter-darkness proxy for an LFP-equipped snow cabin.",
    profile: "Tokyo, Japan",
    appliances: [
      "Refrigerator (modern, mid-size)",
      "Mini-split heat pump (heating mode)",
      "LED light bulb",
      "Laptop or desktop computer",
    ],
    dailyKwh: 10,
    tariff: 0.3,
    currency: "JPY",
    goal: { mode: "offgrid", tier: "tier99" },
    chemistry: "lfp",
    bounds: { pvKw: [0.1, 50], battKwh: [0.1, 300], paybackYears: [0, 100] },
  },
  {
    id: "amelia",
    name: "Amelia",
    region: "Oceania",
    story: "Perth outback dust, extreme heat, and a stock-water pump.",
    profile: "Perth, Australia",
    appliances: [
      "Water pump (shallow/pressure tank 120V)",
      "Refrigerator (modern, mid-size)",
      "Ceiling or desk fan",
      "LED light bulb",
    ],
    dailyKwh: 7,
    tariff: 0.3,
    currency: "AUD",
    goal: { mode: "offgrid", tier: "tier99" },
    chemistry: "lfp",
    bounds: { pvKw: [0.1, 50], battKwh: [0.1, 300], paybackYears: [0, 100] },
  },
  {
    id: "oluwaseun",
    name: "Oluwaseun",
    region: "Southern Africa",
    story:
      "Johannesburg home planning around load-shedding and winter rationing.",
    profile: "Johannesburg, South Africa",
    appliances: [
      "Refrigerator (modern, mid-size)",
      "LED light bulb",
      "Phone charger",
      "Laptop or desktop computer",
    ],
    dailyKwh: 8,
    tariff: 0.14,
    currency: "ZAR",
    goal: { mode: "offgrid", tier: "tier99" },
    chemistry: "lfp",
    bounds: { pvKw: [0.1, 50], battKwh: [0.1, 300], paybackYears: [0, 100] },
  },
  {
    id: "kai",
    name: "Kai",
    region: "Pacific Islands",
    story: "Suva island resort with cyclone risk and generator backup.",
    profile: "Suva, Fiji",
    appliances: [
      "Refrigerator (modern, mid-size)",
      "Chest freezer",
      "Ceiling or desk fan",
      "Water pump (shallow/pressure tank 120V)",
    ],
    dailyKwh: 6,
    tariff: 0.3,
    currency: "FJD",
    goal: { mode: "offgrid", tier: "tier95" },
    chemistry: "naion",
    bounds: { pvKw: [0.1, 50], battKwh: [0.1, 300], paybackYears: [0, 100] },
  },
  {
    id: "eva",
    name: "Eva",
    region: "Central Europe",
    story: "Berlin apartment balancing feed-in and self-consumption.",
    profile: "Berlin, Germany",
    appliances: [
      "Refrigerator (modern, mid-size)",
      "LED light bulb",
      "Washing machine",
      "Laptop or desktop computer",
    ],
    dailyKwh: 12,
    tariff: 0.35,
    currency: "EUR",
    goal: { mode: "gridtie", cut: 0.8 },
    chemistry: "lfp",
    bounds: { pvKw: [0.1, 60], battKwh: [0, 150], paybackYears: [0, 100] },
  },
];

export function personaById(id) {
  return PERSONAS.find((persona) => persona.id === id) || null;
}

export function applianceNames(persona) {
  return [...persona.appliances];
}
